### ISSUE TITLE
Camera is not showing up in Control panel, but can be viewed through settings to test.

### ISSUE THREAD

**Issue by DonChooluvit** [OctoPrint/OctoPi-UpToDate#7]
### What OctoPi-UpToDate modification is involved?

01-update-octoprint

### The problem

1. camera stream does not load on SLA-Control tab
2. going through settings>Webacm and Timelapse>MJPEG stream  [/webcam/?action=stream], the camera is present and viewable

### Please confirm you have understood that you can ONLY report issues with the particular OctoPi-UpToDate build scripts here, not general OctoPrint or OctoPi issues.

- [X] I confirm that my issue is **NOT** about OctoPrint.
- [X] I confirm that my issue is **NOT** about OctoPi.
- [X] I confirm that my issue is **ONLY** about OctoPi-UpToDate.

### Additional information & file uploads

![Screenshot 2023-05-24 144220](https://github.com/OctoPrint/OctoPi-UpToDate/assets/122469185/32c64dd8-a7c1-4271-a215-715000f562a6)
![Screenshot 2023-05-24 144454](https://github.com/OctoPrint/OctoPi-UpToDate/assets/122469185/46b6a34c-a5c3-4704-b351-6502015fcaaf)

**Comment by foosel** [comment]
SLA control tab is neither a bundled plugin nor included on OctoPi -UpToDate, so I won't be able to help you here. I suggest you take it to the plugin maintainer instead.
